export default {
    CHANGE: "CHANGE",
    TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
    GET_VIDEOS: "GET_VIDEOS",
    GET_VIDEOS_RESPONSE: "GET_VIDEOS_RESPONSE",
    ADD_VIDEO: "ADD_VIDEO",
    DELETE_VIDEO: "DELETE_VIDEO",
    EDIT_VIDEO: "EDIT_VIDEO",
};
